name: Tests
on: push
jobs:
  actions:
    runs-on: ubuntu-latest
    steps:
    - name: Copia repositorio
      uses: actions/checkout@v2
    - name: Construye imagen
      run: docker build --tag streamlit_example .
    - name: Verifica el formato
      run: docker run streamlit_example make check
    - name: Corre pruebas
      run: docker run streamlit_example make coverage
    - name: Evalúa resistencia a mutaciones
      run: docker run streamlit_example make mutants
